### ISSUE TITLE
Error when running in Workflow

### ISSUE THREAD

**Issue by apgapg** [TheDotLabs/todo-asana-action#1]
```
/home/runner/work/_actions/TheDotLabs/todo-asana-action/v1.0.0/node_modules/nodegit/dist/nodegit.js:16
    throw ex;
    ^

Error: /home/runner/work/_actions/TheDotLabs/todo-asana-action/v1.0.0/node_modules/nodegit/build/Release/nodegit.node: invalid ELF header
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1025:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/TheDotLabs/todo-asana-action/v1.0.0/node_modules/nodegit/dist/nodegit.js:12:12)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
```

**Comment by apgapg** [comment]
Fixed. This was nodegit @types dev dependency
